spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQAoHYxJEzTcceZJqT+TGIq0jXMr6aALI85lEY1k0pCQvsQLv3oNl04CmKRNOy0DCImijdhPneWGS2UzIstOaobNc7jV9m7vxfcy//exRB+UN8uc9gtuhdeVO+XHBLy0jLHtFQDnyKwtDzHqtK0kvpVMQpd3vFntJvV035snP3jiv9L1urqbeykwrlp6Jt2pE8sGUSMxv6J4vn7ka6dhW4tKfC0g1OcyaU45VBmMb6+ew8jxsemiz9vbZ1FsymsE9LtsR6jVvZeu10vlBt9qCcQFgXrvntu0dM5i0ofTbgN6Uan9X6mVebFFV16A6vHyAdRq11wOGjqoaFhvaXgy/kTjqC4gSygwhKkQhhecKmzpQcmK2EjqtMIqhZLPY7M4OBw='

token:
  expiration_time: 86400000
  secret: '{cipher}AQCSg7VZ3szzSzFFM7vJJSh+yHKAbDAA8IHC4pZ+AwjSjwIQ4aki4X1UkuoGSngzLgChXnydKkabtj0HS7IwbtlkawhIHH61jv8jK6UZsB6UgBsJolh7e0fLonsuN7Xe2a1LSQLX/u0fUJYw+YbWQ2ouZ+aLVRydn3IdyOYrmWifOEW583BzMB99BsAmTrVU9/zcDrpyUffLz71dJvucy3lO5ww22cp4rJNp7koriabUq7Kk6Gf8F4NItjsTRZpJrHCIqVVCA/KkBRovz/siWEgDi6yGPBbwNnLVUNuR5ACdHMh9NfOr1uMAmHU5GYRzEdHV7sdIOCsNd8mXy/xJLd1iLKAfCiA7F6xL4ue1aW7+zjgxAcT5gYDp4xcTAcYppwk='

gateway:
  ip: 192.168.0.3